[project]
name = "webapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Samit Koyom", email = "samitkoyom@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "psycopg[binary]>=3.3.4",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
